### ISSUE TITLE
Blender 2.92 wont install wont do anything

### ISSUE THREAD

**Issue by InsaneXade** [Jandals/HairNet#30]
I tried every version I could find and I still cannot use it. I really want to for my webcomic but I can't do anything. Any ideas or have I missed something?

**Comment by Jandals** [comment]
Tell me more about what's going wrong. Do you get an error message? Which version/ZIP file are you trying to install?

**Comment by InsaneXade** [comment]
nothing at all,  I get the it was installed and nothing happens. it doesn't
automatically become the only one active like say MB-Lab. I can't locate it
when I search for "hair" nothing.

**Comment by Jandals** [comment]
It looks like I made a mistake in making the Zip file. The zip file has three .py files inside it which are supposed to go into a folder called “hairNet” inside Blender’s “addons” folder. But that isn’t happening. If you’re up for it, you could fix the files by moving them. And if not, I will fix the Zip file tonight so that it installs correctly.

sorry!

**Comment by InsaneXade** [comment]
ok, it works now. Thank you. I had to locate the folder. I thought it would
to it in the install folder so it took my by surprise that it uses the app
data folder
