### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by SuraiaSilverbell** [Jandals/HairNet#4]
I've tried to install HairNet, eventually using the .py file. But when I try and enable to the addon I get a traceback error.

> File "... Blender\2.79\scripts\modules\addon_utils.py", line 331, in enable mod =_import_(module_name)
> File "...AppData...\HairNet.py", line 418 meshKind : StringProperty()
> 
> SyntaxError: invalid syntax.

I'm not sure if something went wrong with the installation or if something else is going on.

**Comment by JakubOleskevic** [comment]
I am having an exact same issue! 
Is there any way to find previous add on versions?

**Comment by Jandals** [comment]
Whoops! I'm going to guess that you're both using Blender v2.79. And the only easily-available version is for Blender 2.8, witch doesn't work yet. That's careless of me.

You should be able to download a working .py file for 2.79 here:

https://github.com/Jandals/HairNet/tree/c79e2a03faf5e779be62b0cd9474ba2937855f5f/src

You'll have to either put this file into your addons folder manually, or ZIP it before trying to add it through Blender's Preferences window.

I'll see if I can reorganize the GitHub pages so that the working version is still available.

**Comment by Jandals** [comment]
I added a  release for the version that works with Blender 2.79. It's here:
https://github.com/Jandals/HairNet/releases

I'd be glad to hear whether this fixes the problem for you.

**Comment by JakubOleskevic** [comment]
> I added a release for the version that works with Blender 2.79. It's here:
> https://github.com/Jandals/HairNet/releases
> 
> I'd be glad to hear whether this fixes the problem for you.

Hey Jandals!!

Thank you so much for uploading the older version! It worked perfectly for me on, indeed, 2.79! 
Literally a life saver, so greatly appreciated!

**Comment by Jandals** [comment]
Thank you for the feedback. I'm glad you've got a working version.

I'm sorry about the confusion.
