### ISSUE TITLE
hirenet is not showing in the list after installing and it gives me a massage

### ISSUE THREAD

**Issue by gassem159** [Jandals/HairNet#47]
ok every time i instill it gives me this 

Modules Installed () from 'C:\\Users\\Gassem\\Desktop\\HairNet-master.zip' into 'C:\\Users\\Gassem\\AppData\\Roaming\\Blender Foundation\\Blender\\3.1\\scripts\\addons'

here screen a shot of the issues
https://c.top4top.io/p_2319il8do1.jpg

**Comment by Jandals** [comment]
This error happens when you download the repository directly, instead of going to one of the "releases."

The problem is that the file GitHub creates is called "hairnet-master.zip" and Blender needs it to be called "hairnet.zip". Plus or minus the capitals; i'm not sure if they're important…

You *might* be able to fix it by just renaming the zip file, but Git may package things strangely so redownloading is more reliable.
