### ISSUE TITLE
2.8: generated guide hairs do not follow edges of original sheet

### ISSUE THREAD

**Issue by killarny** [Jandals/HairNet#5]
Using the latest release in Blender 2.8, the generated guide hairs are not following the path of the edges in the original sheet that I constructed.

[video demonstration](https://i.imgur.com/oqUYuYE.gifv)

The same process works properly in the latest version of the addon for 2.79.

**Comment by Jandals** [comment]
Yes. This happens because, somewhere in the API for Blender 2.8, the control points in the guide hairs fail to report their location. I have to wait for Blender to be fixed before I can do any more to update HairNet for 2.8.
Thanks for confirming that this is still an issue. I should add a note someplace visible that this is an ongoing problem. I'm sorry that I didn't have that warning up already.

**Comment by ale-tachibana** [comment]
Did you try to evaluate the object first?

despgraph = bpy.context.evaluated_depsgraph_get()
evaluated_object = despgraph.objects.get(bpy.context.selected_objects[0].name, None)

then
evaluated_object .particle_systems[0].particles.items()[0][1].hair_keys.items()[0][1].co
