### ISSUE TITLE
Is jandals working on this anymore?

### ISSUE THREAD

**Issue by Darkrain111** [Jandals/HairNet#51]
I'm asking because they've been inactive for a long time and the newer questions are unanswered, plus hairnet can barely been used without multiple errors of different kinds, I can only use the emit hair on self in a very limited way, I've been meaning to ask several questions but I don't know if they'll ever be answered.

**Comment by Jandals** [comment]
I can’t say I’ve been “working” on hairnet because I haven’t had time to put into resolving issues.

a lot of the problems that come up stem from how often something in the particles api changes. So I can imagine there are some new errors as Blender advances in versions but I haven’t been able to keep up with the changes.

I also miss a lot of the conversations about the add on because they get posted in places I don’t see. So I’m always surprised to hear that anyone is using it.

**Comment by Darkrain111** [comment]
That's understandable, I imagine it'd get tiring when you spend hours fixing something only to have it break a day later because a new version came out.
